---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by nonacosa.
--- DateTime: 2022/2/7 9:11 PM
---

if a < 0 then a = 0 end

if a < b then return a else return b end

-- elseif
if op == "+" then
    r = a + b
elseif op == "-" then
    r = a - b
end

-- while
local i = 1
while a[i] do
    print(a[i])
    i = i + 1
end

-- repeat
local line
repeat
    line = io.read()
until line ~= ""
print(line)

-- for

for var = exp1,exp2,exp3 do
    -- do something
end

-- break
local i = 1
while a[i] do
    if a[i] == v then return i end
    i = i + 1 -- not support i ++
end

-- goto

-- ::redo::     +      ::continue::
