---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by nonacosa.
--- DateTime: 2022/2/7 3:30 PM
---

function fact(n)
    if n < 0 then
        return 1
    else
        return n * fact(n -1)
    end
end

a = io.read("*n")
print(fact(a))

print(type(nil) == nil)
