---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by nonacosa.
--- DateTime: 2022/2/7 4:39 PM
---

-- 唯一的例外就是，当函数只有一个参数且该参数是字符串常量或表构造器时，括号是可选的
dofile("hello.lua")
dofile "hello.lua"

-- 多返回值
s,e = string.find("hello lua users","lua")
print(s,e)


-- 自定义多返回值

function multipleResults()
    return 1,3
end

print(multipleResults())