---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by nonacosa.
--- DateTime: 2022/2/7 11:52 PM
--- 最有价值：调用 C

-- 声明 C 函数或数据结构
ffi.cedf[[
struct dummy{};											// 注意这里需要使用 C 的注释形式
double sqrt(double x);
int gethostname(char *name, size_t len);
]]
-- 声明结束

local int_t = ffi.typeof("int")							-- C 整数类型对象
local char_arr_t = ffi_typeof("char[?]")				-- C 字符串数组类型对象

local a_int = ffi_new(int_t)							-- 创建一个整数对象
local char_arr = char_arr_t(10)							-- 创建一个字符数组，长度 10