---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by nonacosa.
--- DateTime: 2022/2/7 11:25 PM
--- 前提是下载 luaJit  http://luajit.org

-- luajit luaJIT.lua

print(jit.version)
print(jit.version_num)
print(jit.os)
print(jit.arch)
print(jit.status())