---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by nonacosa.
--- DateTime: 2022/2/7 3:45 PM
---

print(string.format("%a",419))
print(0x1.a3p+8)
print(math.type(0x1.a3p+8))

-- 强转浮点
print(-3 + 0.0)

-- 强转整形
print(2 ^ 53 | 0)

-- 强制拼接
print(10 .. 20)

-- 字符串强转浮点
print("10" + 1)

-- 强转整形
print(tonumber("-3"))
print(tonumber("10e4"))
print(tonumber("100101",2))
print(tonumber("fff",16))