---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by nonacosa.
--- DateTime: 2022/2/7 4:48 PM
---

-- 可变长参

function add(...)
    local s = 0
    for _, v in ipairs{...} do
        print("foreach value is : " .. v)
        s = s + v
    end
    return s
end

print(add(3,4,5,6,6))

-- 内部恒定参数
function add2(...)
    local a,b,c = ...;
    return a + b + c;
end

print(add2(1,3,4))