---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by nonacosa.
--- DateTime: 2022/2/7 3:56 PM
---

print(string.rep("abc",4))
print(string.reverse("abc"))
print(string.lower("A Long Line"))
print(string.upper("A Long Line"))

-- lua index from 1
print(string.byte("abc",1,3))