---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by nonacosa.
--- DateTime: 2022/2/7 11:26 PM
--- 前提是下载 luaJit  http://luajit.org



local table_new = require "table.new"
local table_clear = require "table.clear"

local t = table_new(10,0)
t[1] = 1;
print(#t)
print(unpack(t))
table_clear(t)
print(#t)