---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by nonacosa.
--- DateTime: 2022/2/7 9:06 PM
---

x = 10
local i = 1

while i<= x do
    local x = i * 2 -- 循环体局部
    print(x)
    i = i + 1
end

print("---")

if i > 20 then
    local x -- 对 then 全局
    x = 20
    print(x + 2)
else
    print(x) -- 去哪聚
end

print(x) -- 全局